[package]
name = "bevy-moonracer"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
roxmltree = "0.18"
itertools = "0.11"

[dependencies.bevy_wasm_window_resize]
git = "https://github.com/TristanCacqueray/bevy_wasm_window_resize.git"
branch = "bevy-devel"

[dependencies.bevy]
git = "https://github.com/TristanCacqueray/bevy.git"
branch = "wgpu"
default-features = false
features = [
  # core
  "bevy_core_pipeline",
  "bevy_pbr",
  "bevy_render",
  "bevy_text",
  "bevy_ui",
  "multi-threaded",
  "bevy_winit",

  # native video
  # "wayland",

  # audio
  "bevy_audio",
  "vorbis",
]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bevy]
git = "https://github.com/TristanCacqueray/bevy.git"
branch = "wgpu"
default-features = false
features = [
  "dynamic_linking",
  "wayland",
]

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[[example]]
name = "level"
path = "src/level_loader_test.rs"
doc-scrape-examples = true
